### ISSUE TITLE
Flux Cycles

### ISSUE THREAD

**Issue by claire-kz** [IanKingr/FieldGuideToFantasticBeasts#2]
- Add actions for fetching beast reviews, and figure out where you want to store this info

**Comment by IanKingr** [comment]
Hi Claire, I added the changes you recommended including
- MVP: Adding Create Beast Entries and Create Reviews as MVPs
- Flux Cycle: Adding actions for fetching beast reviews and a review store
- Schema: Removing unnecessary columns and modifying schema to reflect new Review component

I'm a bit worried that my Flux Cycle might have mistakes at the moment, but otherwise I'm ok. Thanks again for the feedback!
